version: '3.8'

services:
  apache:
    image: docker.io/library/httpd:2.4
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
      - ./apache-config:/usr/local/apache2/conf
    depends_on:
      - php
    networks:
      - app_network
    mem_limit: 128m

  php:
    image: docker.io/library/php:8.2-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network
    mem_limit: 128m

  mysql:
    image: docker.io/library/mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    mem_limit: 256m

  node:
    image: docker.io/library/node:16
    container_name: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm install -D tailwindcss && npx tailwindcss init && npm run build"
    networks:
      - app_network
    mem_limit: 256m

  vue:
    image: docker.io/library/node:16
    container_name: vue
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm run serve"
    ports:
      - "8080:8080"
    networks:
      - app_network
    mem_limit: 256m

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge